<?php

namespace App\Http\Controllers;

use App\Actions\GenerateSalespageContent;
use App\Enums\SalespageStyle;
use App\Exceptions\AiGenerationException;
use App\Http\Requests\GenerateSalespageRequest;
use App\Http\Requests\UpdateSalespageRequest;
use App\Models\AiProviderSetting;
use App\Models\Funnel;
use App\Support\ContentBlockSanitizer;
use Illuminate\Http\RedirectResponse;
use Inertia\Inertia;
use Inertia\Response;

class SalespageController extends Controller
{
    /**
     * Show the salespage editor for the given funnel.
     */
    public function edit(Funnel $funnel): Response
    {
        $this->authorize('update', $funnel);

        $funnel->load(['salespage', 'product']);

        return Inertia::render('funnels/salespage', [
            'funnel' => $funnel,
            'salespage' => $funnel->salespage,
            'aiProviderSettings' => AiProviderSetting::query()
                ->where('is_active', true)
                ->get(['id', 'label', 'provider']),
        ]);
    }

    /**
     * Manually update the salespage content.
     */
    public function update(UpdateSalespageRequest $request, Funnel $funnel): RedirectResponse
    {
        $validated = $request->validated();

        $funnel->salespage()->updateOrCreate([], [
            'title' => $validated['title'],
            'content' => ContentBlockSanitizer::sanitize($validated['content']),
            'style' => $validated['style'],
            'seo_title' => $validated['seo_title'] ?? null,
            'seo_description' => $validated['seo_description'] ?? null,
            'generated_by_ai' => false,
            'published_at' => ($validated['is_published'] ?? false) ? now() : null,
        ]);

        Inertia::flash('toast', ['type' => 'success', 'message' => __('Salespage saved.')]);

        return to_route('funnels.salespage.edit', $funnel);
    }

    /**
     * Generate salespage content using AI.
     */
    public function generate(GenerateSalespageRequest $request, Funnel $funnel, GenerateSalespageContent $action): RedirectResponse
    {
        $validated = $request->validated();
        $setting = AiProviderSetting::query()
            ->where('id', $validated['ai_provider_setting_id'])
            ->firstOrFail();
        $style = SalespageStyle::from($validated['style']);

        try {
            $action($funnel, $setting, $style, $validated['brief'] ?? null);

            Inertia::flash('toast', ['type' => 'success', 'message' => __('Salespage generated by AI.')]);
        } catch (AiGenerationException $exception) {
            Inertia::flash('toast', ['type' => 'error', 'message' => $exception->getMessage()]);
        }

        return to_route('funnels.salespage.edit', $funnel);
    }
}
