<?php

namespace App\Http\Controllers;

use App\Actions\GenerateSalespageContent;
use App\Enums\SalespageStyle;
use App\Exceptions\AiGenerationException;
use App\Http\Requests\GenerateSalespageRequest;
use App\Http\Requests\UpdateSalespageRequest;
use App\Models\AiProviderSetting;
use App\Models\Funnel;
use App\Support\ContentBlockSanitizer;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Storage;
use Inertia\Inertia;
use Inertia\Response;

class SalespageController extends Controller
{
    /**
     * Show the salespage editor for the given funnel.
     */
    public function edit(Funnel $funnel): Response
    {
        $this->authorize('update', $funnel);

        $funnel->load(['salespage', 'product']);

        return Inertia::render('funnels/salespage', [
            'funnel' => $funnel,
            'salespage' => $funnel->salespage,
            'aiProviderSettings' => AiProviderSetting::query()
                ->where('is_active', true)
                ->get(['id', 'label', 'provider']),
        ]);
    }

    /**
     * Manually update the salespage content.
     */
    public function update(UpdateSalespageRequest $request, Funnel $funnel): RedirectResponse
    {
        $validated = $request->validated();
        $content = $this->resolveMediaUploads($request, $validated['content']);

        $funnel->salespage()->updateOrCreate([], [
            'title' => $validated['title'],
            'content' => ContentBlockSanitizer::sanitize($content),
            'style' => $validated['style'],
            'seo_title' => $validated['seo_title'] ?? null,
            'seo_description' => $validated['seo_description'] ?? null,
            'generated_by_ai' => false,
            'published_at' => ($validated['is_published'] ?? false) ? now() : null,
        ]);

        Inertia::flash('toast', ['type' => 'success', 'message' => __('Salespage saved.')]);

        return to_route('funnels.salespage.edit', $funnel);
    }

    /**
     * Store any newly uploaded image/video files for content blocks — the
     * editor sends a raw File object nested in `content.*.data.file` when
     * the admin picks a file to upload (Inertia serializes it into a
     * multipart field automatically) — and swap it for the resulting
     * public URL. Blocks that don't carry a `file` are left untouched.
     *
     * File validation is deliberately kept out of `salespageRules()` and run
     * here as its own scoped `validate()` call instead: adding a
     * `content.*.data.file` rule alongside `content.*.data` there causes
     * Laravel's `validated()` to treat the deeper wildcard rule as
     * authoritative and drop every other sibling key under `data` (text,
     * items, url, ...) that has no rule of its own.
     *
     * @param  array<int, array<string, mixed>>  $content
     * @return array<int, array<string, mixed>>
     */
    private function resolveMediaUploads(UpdateSalespageRequest $request, array $content): array
    {
        $request->validate([
            'content.*.data.file' => ['nullable', 'file', 'max:51200'],
        ]);

        foreach ($content as $index => &$block) {
            if (! is_array($block['data'] ?? null)) {
                continue;
            }

            if ($request->hasFile("content.{$index}.data.file")) {
                $path = $request->file("content.{$index}.data.file")->store('salespage-media', 'public');
                $block['data']['url'] = Storage::disk('public')->url($path);
            }

            unset($block['data']['file']);
        }

        unset($block);

        return $content;
    }

    /**
     * Generate salespage content using AI.
     */
    public function generate(GenerateSalespageRequest $request, Funnel $funnel, GenerateSalespageContent $action): RedirectResponse
    {
        $validated = $request->validated();
        $setting = AiProviderSetting::query()
            ->where('id', $validated['ai_provider_setting_id'])
            ->firstOrFail();
        $style = SalespageStyle::from($validated['style']);

        try {
            $action($funnel, $setting, $style, $validated['brief'] ?? null);

            Inertia::flash('toast', ['type' => 'success', 'message' => __('Salespage generated by AI.')]);
        } catch (AiGenerationException $exception) {
            Inertia::flash('toast', ['type' => 'error', 'message' => $exception->getMessage()]);
        }

        return to_route('funnels.salespage.edit', $funnel);
    }
}
